commit configure changes for water effect
git-svn-id: svn://dyne.org/rastasoft/freej/freej@78 383723c8-4afa-0310-b8a8-b1afb83214fc

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -462,7 +462,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os SET_MAKE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL SDL_CONFIG SDL_CFLAGS SDL_LIBS NASM NASMFLAGS AVIFILE_CONFIG AVIFILE_LDFLAGS AVIFILE_CXXFLAGS AVIFILE_LIBS FT2_CONFIG FT2_CFLAGS FT2_LIBS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os SET_MAKE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL SDL_CONFIG SDL_CFLAGS SDL_LIBS AVIFILE_CONFIG AVIFILE_LDFLAGS AVIFILE_CXXFLAGS HAVE_AVIFILE AVIFILE_LIBS FT2_CONFIG FT2_CFLAGS FT2_LIBS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1033,7 +1033,7 @@ Optional Features:
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
   --disable-sdltest       Do not try to compile and run a test SDL program
-  --enable-nasm           use nasm assembly blitters on x86 default=yes
+  --enable-avi            compile with Avi Layer linking avifile (auto)
   --disable-freetypetest  Do not try to compile and run
                           a test FreeType program
 
@@ -1047,7 +1047,6 @@ Optional Packages:
                           include additional configurations [automatic]
   --with-sdl-prefix=PFX   Prefix where SDL is installed (optional)
   --with-sdl-exec-prefix=PFX Exec prefix where SDL is installed (optional)
-  --with-avifile          compile with avifile MOVIE LAYER
   --with-ft-prefix=PREFIX
                           Prefix where FreeType is installed (optional)
   --with-ft-exec-prefix=PREFIX
@@ -3957,7 +3956,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3960 "configure"' > conftest.$ac_ext
+  echo '#line 3959 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5032,7 +5031,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5035:" \
+echo "$as_me:5034:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6037,11 +6036,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6040: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6039: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6044: \$? = $ac_status" >&5
+   echo "$as_me:6043: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6269,11 +6268,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6272: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6271: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6276: \$? = $ac_status" >&5
+   echo "$as_me:6275: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6336,11 +6335,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6339: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6338: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6343: \$? = $ac_status" >&5
+   echo "$as_me:6342: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8348,7 +8347,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8351 "configure"
+#line 8350 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8446,7 +8445,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8449 "configure"
+#line 8448 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10578,11 +10577,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10581: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10580: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10585: \$? = $ac_status" >&5
+   echo "$as_me:10584: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -10645,11 +10644,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10648: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10647: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10652: \$? = $ac_status" >&5
+   echo "$as_me:10651: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11888,7 +11887,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11891 "configure"
+#line 11890 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11986,7 +11985,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11989 "configure"
+#line 11988 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12808,11 +12807,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12811: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12810: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12815: \$? = $ac_status" >&5
+   echo "$as_me:12814: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -12875,11 +12874,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12878: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12877: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12882: \$? = $ac_status" >&5
+   echo "$as_me:12881: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14815,11 +14814,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14818: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14817: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14822: \$? = $ac_status" >&5
+   echo "$as_me:14821: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15047,11 +15046,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15050: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15049: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15054: \$? = $ac_status" >&5
+   echo "$as_me:15053: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15114,11 +15113,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15117: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15116: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15121: \$? = $ac_status" >&5
+   echo "$as_me:15120: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17126,7 +17125,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17129 "configure"
+#line 17128 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17224,7 +17223,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17227 "configure"
+#line 17226 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18231,7 +18230,7 @@ LIBTOOL='$(SHELL) $(top_builddir)/libtool'
 
 
 
-CFLAGS="-g -Wall -O4 -D_REENTRANT -fomit-frame-pointer -mcpu=${host_cpu} -finline-functions -ffast-math -malign-double -funroll-loops"
+CFLAGS="-g -Wall -O4 -pipe -D_REENTRANT -fomit-frame-pointer -mcpu=${host_cpu} -finline-functions -ffast-math -malign-double -funroll-loops"
 LIBS="-lpthread -lm -ldl -lpng"
 
 echo "$as_me:$LINENO: checking for ANSI C header files" >&5
@@ -19953,88 +19952,7 @@ _ACEOF
 
 
 
-
-CheckNASM()
-{
-        case $target in
-        i?86*)
-            ;;
-        *)
-        # Nope, bail early.
-            return
-            ;;
-    esac
-        # Check whether --enable-nasm or --disable-nasm was given.
-if test "${enable_nasm+set}" = set; then
-  enableval="$enable_nasm"
-  checking nasm
-else
-  enable_nasm=yes
-fi;
-    if test x$enable_nasm = xyes; then
-        # Extract the first word of "nasm", so it can be a program name with args.
-set dummy nasm; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_path_NASM+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $NASM in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_NASM="$NASM" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_path_NASM="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-  ;;
-esac
-fi
-NASM=$ac_cv_path_NASM
-
-if test -n "$NASM"; then
-  echo "$as_me:$LINENO: result: $NASM" >&5
-echo "${ECHO_T}$NASM" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-        if test x$NASM = x -o x$NASM = x'"$NASM"'; then
-            : # nasm isn't installed
-        else
-            case $ARCH in
-              win32)
-                  NASMFLAGS="-f win32"
-                  ;;
-              *)
-                  NASMFLAGS="-f elf"
-                  ;;
-            esac
-
-            CFLAGS="$CFLAGS -I\$(top_srcdir)/src/asm"
-        fi
-    fi
-}
-
-
-# Check whether --with-avifile or --without-avifile was given.
-if test "${with_avifile+set}" = set; then
-  withval="$with_avifile"
-     echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-    AVI_LIBS=""
+AVI_LIBS=""
 
   HAVE_AVIFILE="no"
 
@@ -20186,22 +20104,37 @@ fi
     AVIFILE_LIBS="-laviplay -lXv -lXxf86vm"
   fi
 
-    if test x$HAVE_AVIFILE = xyes; then
+
+if test -z $HAVE_AVIFILE; then
+echo "Error in avifile check, HAVE_AVIFILE is not declared"
+fi
+# Check whether --enable-avi or --disable-avi was given.
+if test "${enable_avi+set}" = set; then
+  enableval="$enable_avi"
+
+# to this when --enable-avi is selected (check the value!)
+if test x$HAVE_AVIFILE = xyes -a ! x$enableval = xno; then
 
 cat >>confdefs.h <<\_ACEOF
 #define WITH_AVIFILE 1
 _ACEOF
 
-       have_avilayer=yes
-    else
-       have_avilayer=no
-    fi
+  have_avilayer=yes
 
+fi
 else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi;
 
+# to this by default, when --enable-avi is not selected
+if test x$HAVE_AVIFILE = xyes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define WITH_AVIFILE 1
+_ACEOF
+
+  have_avilayer=yes
+
+fi
+fi;
 
 
 # Check whether --with-ft-prefix or --without-ft-prefix was given.
@@ -20589,7 +20522,7 @@ CXXFLAGS="$CFLAGS $SDL_CFLAGS $AVIFILE_CXXFLAGS $FT2_CFLAGS"
 #AC_SUBST(LIBS)
 
 
-                                                                                                                                                      ac_config_files="$ac_config_files Makefile src/Makefile src/include/Makefile filters/Makefile filters/delaygrab/Makefile filters/absdiff/Makefile filters/rotozoom/Makefile filters/simura/Makefile filters/baltan/Makefile filters/vertigo/Makefile filters/transform/Makefile filters/blurzoom/Makefile filters/edge/Makefile filters/backlight/Makefile filters/blur/Makefile"
+                                                                                                                                                                          ac_config_files="$ac_config_files Makefile src/Makefile src/include/Makefile filters/Makefile filters/delaygrab/Makefile filters/absdiff/Makefile filters/rotozoom/Makefile filters/simura/Makefile filters/baltan/Makefile filters/vertigo/Makefile filters/transform/Makefile filters/blurzoom/Makefile filters/edge/Makefile filters/backlight/Makefile filters/blur/Makefile filters/ripple/Makefile filters/water/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -21160,6 +21093,8 @@ do
   "filters/edge/Makefile" ) CONFIG_FILES="$CONFIG_FILES filters/edge/Makefile" ;;
   "filters/backlight/Makefile" ) CONFIG_FILES="$CONFIG_FILES filters/backlight/Makefile" ;;
   "filters/blur/Makefile" ) CONFIG_FILES="$CONFIG_FILES filters/blur/Makefile" ;;
+  "filters/ripple/Makefile" ) CONFIG_FILES="$CONFIG_FILES filters/ripple/Makefile" ;;
+  "filters/water/Makefile" ) CONFIG_FILES="$CONFIG_FILES filters/water/Makefile" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
@@ -21315,11 +21250,10 @@ s,@LIBTOOL@,$LIBTOOL,;t t
 s,@SDL_CONFIG@,$SDL_CONFIG,;t t
 s,@SDL_CFLAGS@,$SDL_CFLAGS,;t t
 s,@SDL_LIBS@,$SDL_LIBS,;t t
-s,@NASM@,$NASM,;t t
-s,@NASMFLAGS@,$NASMFLAGS,;t t
 s,@AVIFILE_CONFIG@,$AVIFILE_CONFIG,;t t
 s,@AVIFILE_LDFLAGS@,$AVIFILE_LDFLAGS,;t t
 s,@AVIFILE_CXXFLAGS@,$AVIFILE_CXXFLAGS,;t t
+s,@HAVE_AVIFILE@,$HAVE_AVIFILE,;t t
 s,@AVIFILE_LIBS@,$AVIFILE_LIBS,;t t
 s,@FT2_CONFIG@,$FT2_CONFIG,;t t
 s,@FT2_CFLAGS@,$FT2_CFLAGS,;t t
