first experimental libglade-2.0 gtk+-2.0 controller implementation
git-svn-id: svn://dyne.org/rastasoft/freej/freej@91 383723c8-4afa-0310-b8a8-b1afb83214fc

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -462,7 +462,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os SET_MAKE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL SDL_CONFIG SDL_CFLAGS SDL_LIBS AVIFILE_CONFIG AVIFILE_LDFLAGS AVIFILE_CXXFLAGS HAVE_AVIFILE AVIFILE_LIBS FT2_CONFIG FT2_CFLAGS FT2_LIBS PNG_LIBS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os SET_MAKE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL SDL_CONFIG SDL_CFLAGS SDL_LIBS AVIFILE_CONFIG AVIFILE_LDFLAGS AVIFILE_CXXFLAGS HAVE_AVIFILE AVIFILE_LIBS FT2_CONFIG FT2_CFLAGS FT2_LIBS PNG_LIBS PKG_CONFIG GLADE2_CFLAGS GLADE2_LIBS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -19610,6 +19610,110 @@ fi
 fi;
 
 
+  succeeded=no
+
+  if test -z "$PKG_CONFIG"; then
+    # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_PKG_CONFIG" && ac_cv_path_PKG_CONFIG="no"
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+
+if test -n "$PKG_CONFIG"; then
+  echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
+echo "${ECHO_T}$PKG_CONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  fi
+
+  if test "$PKG_CONFIG" = "no" ; then
+     echo "*** The pkg-config script could not be found. Make sure it is"
+     echo "*** in your path, or set the PKG_CONFIG environment variable"
+     echo "*** to the full path to pkg-config."
+     echo "*** Or see http://www.freedesktop.org/software/pkgconfig to get pkg-config."
+  else
+     PKG_CONFIG_MIN_VERSION=0.9.0
+     if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
+        echo "$as_me:$LINENO: checking for libglade-2.0 >= 2.0.0 gthread-2.0 >= 2.0.0" >&5
+echo $ECHO_N "checking for libglade-2.0 >= 2.0.0 gthread-2.0 >= 2.0.0... $ECHO_C" >&6
+
+        if $PKG_CONFIG --exists "libglade-2.0 >= 2.0.0 gthread-2.0 >= 2.0.0" ; then
+            echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+            succeeded=yes
+
+            echo "$as_me:$LINENO: checking GLADE2_CFLAGS" >&5
+echo $ECHO_N "checking GLADE2_CFLAGS... $ECHO_C" >&6
+            GLADE2_CFLAGS=`$PKG_CONFIG --cflags "libglade-2.0 >= 2.0.0 gthread-2.0 >= 2.0.0"`
+            echo "$as_me:$LINENO: result: $GLADE2_CFLAGS" >&5
+echo "${ECHO_T}$GLADE2_CFLAGS" >&6
+
+            echo "$as_me:$LINENO: checking GLADE2_LIBS" >&5
+echo $ECHO_N "checking GLADE2_LIBS... $ECHO_C" >&6
+            GLADE2_LIBS=`$PKG_CONFIG --libs "libglade-2.0 >= 2.0.0 gthread-2.0 >= 2.0.0"`
+            echo "$as_me:$LINENO: result: $GLADE2_LIBS" >&5
+echo "${ECHO_T}$GLADE2_LIBS" >&6
+        else
+            GLADE2_CFLAGS=""
+            GLADE2_LIBS=""
+            ## If we have a custom action on failure, don't print errors, but
+            ## do set a variable so people can do so.
+            GLADE2_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libglade-2.0 >= 2.0.0 gthread-2.0 >= 2.0.0"`
+            echo $GLADE2_PKG_ERRORS
+        fi
+
+
+
+     else
+        echo "*** Your version of pkg-config is too old. You need version $PKG_CONFIG_MIN_VERSION or newer."
+        echo "*** See http://www.freedesktop.org/software/pkgconfig"
+     fi
+  fi
+
+  if test $succeeded = yes; then
+
+
+cat >>confdefs.h <<\_ACEOF
+#define WITH_GLADE2 1
+_ACEOF
+
+  have_glade2=yes
+
+  else
+     { { echo "$as_me:$LINENO: error: Library requirements (libglade-2.0 >= 2.0.0 gthread-2.0 >= 2.0.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (libglade-2.0 >= 2.0.0 gthread-2.0 >= 2.0.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
 
 if test "${ac_cv_header_dmalloc_h+set}" = set; then
   echo "$as_me:$LINENO: checking for dmalloc.h" >&5
@@ -19774,7 +19878,7 @@ fi;
 
 fi
 
-CXXFLAGS="$CFLAGS $SDL_CFLAGS $AVIFILE_CXXFLAGS $FT2_CFLAGS"
+CXXFLAGS="$CFLAGS $SDL_CFLAGS $AVIFILE_CXXFLAGS $FT2_CFLAGS $GLADE2_CFLAGS"
 CFLAGS="$CFLAGS $SDL_FLAGS"
 #echo "LIBS are $LIBS"
 #AC_SUBST(LIBS)
@@ -20519,6 +20623,9 @@ s,@FT2_CONFIG@,$FT2_CONFIG,;t t
 s,@FT2_CFLAGS@,$FT2_CFLAGS,;t t
 s,@FT2_LIBS@,$FT2_LIBS,;t t
 s,@PNG_LIBS@,$PNG_LIBS,;t t
+s,@PKG_CONFIG@,$PKG_CONFIG,;t t
+s,@GLADE2_CFLAGS@,$GLADE2_CFLAGS,;t t
+s,@GLADE2_LIBS@,$GLADE2_LIBS,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
