some coding done in Palestine (Bethlehem and Ramallah): new PNG image layer, rewritten fps calculator, added fps limiter (also with help from Megabug), limited to 32bpp screens, small docu updates
git-svn-id: svn://dyne.org/rastasoft/freej/freej@31 383723c8-4afa-0310-b8a8-b1afb83214fc

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -823,7 +823,6 @@ Optional Features:
   --disable-libtool-lock  avoid locking (might break parallel builds)
   --disable-sdltest       Do not try to compile and run a test SDL program
   --enable-nasm           use nasm assembly blitters on x86 default=yes
-  --enable-efence	  link electricfence libs for mem debugging no
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -832,6 +831,7 @@ Optional Packages:
   --with-pic              try to use only PIC/non-PIC objects default=use both
   --with-sdl-prefix=PFX   Prefix where SDL is installed (optional)
   --with-sdl-exec-prefix=PFX Exec prefix where SDL is installed (optional)
+  --with-avifile          link to avifile for avi layer playback
 
 Some influential environment variables:
   CC          C compiler command
@@ -6451,7 +6451,7 @@ LIBTOOL='$(SHELL) $(top_builddir)/libtool'
 
 # Prevent multiple expansion
 
-CFLAGS="-g -Wall -O3 -fomit-frame-pointer -march=${host_cpu} -mcpu=${host_cpu} -finline-functions -ffast-math -malign-double -funroll-loops"
+CFLAGS="-g -Wall -O3 -D_REENTRANT -fomit-frame-pointer -march=${host_cpu} -mcpu=${host_cpu} -finline-functions -ffast-math -malign-double -funroll-loops"
 
 echo "$as_me:6456: checking for ANSI C header files" >&5
 echo $ECHO_N "checking for ANSI C header files... $ECHO_C" >&6
@@ -7944,23 +7944,74 @@ fi
     fi
 }
 
-# Check whether --enable-efence or --disable-efence was given.
-if test "${enable_efence+set}" = set; then
-  enableval="$enable_efence"
-  case "${enableval}" in
-		yes) efence=true ;;
-		no) efence=false ;;
-		*) { { echo "$as_me:7953: error: --enable-efence expects either yes or no" >&5
-echo "$as_me: error: --enable-efence expects either yes or no" >&2;}
-   { (exit 1); exit 1; }; } ;;
-	esac
+echo "$as_me:7947: checking for avifile/renderer.h" >&5
+echo $ECHO_N "checking for avifile/renderer.h... $ECHO_C" >&6
+if test "${ac_cv_header_avifile_renderer_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  efence=false
+  cat >conftest.$ac_ext <<_ACEOF
+#line 7953 "configure"
+#include "confdefs.h"
+#include <avifile/renderer.h>
+_ACEOF
+if { (eval echo "$as_me:7957: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:7963: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_cv_header_avifile_renderer_h=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_cv_header_avifile_renderer_h=no
+fi
+rm -f conftest.err conftest.$ac_ext
+fi
+echo "$as_me:7982: result: $ac_cv_header_avifile_renderer_h" >&5
+echo "${ECHO_T}$ac_cv_header_avifile_renderer_h" >&6
+
+if test "$ac_cv_header_avifile_renderer_h" = "yes"; then
+
+echo "$as_me:7987: checking if avifile is present for AVI layer playback" >&5
+echo $ECHO_N "checking if avifile is present for AVI layer playback... $ECHO_C" >&6
+
+# Check whether --with-avifile or --without-avifile was given.
+if test "${with_avifile+set}" = set; then
+  withval="$with_avifile"
+  if test "$withval" = yes; then
+  echo "$as_me:7994: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\EOF
+#define WITH_AVIFILE 1
+EOF
+
+  LIBS="$LIBS -laviplay"
+  AVI_LAYER="avi_layer.cpp"
+  have_avilayer=yes
+else
+  echo "$as_me:8005: result: no : AVI playback layer deactivated" >&5
+echo "${ECHO_T}no : AVI playback layer deactivated" >&6
+  AVI_LAYER=""
+  have_avilayer=no
+fi
+else
+  echo "$as_me:8011: result: no" >&5
+echo "${ECHO_T}no" >&6
 fi;
-if test "$efence" = "true"; then
-	EFENCE_LIBS="-lefence"
-else
-	EFENCE_LIBS=""
+
 fi
 
 CFLAGS="$CFLAGS"
@@ -8047,7 +8098,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:8050: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:8101: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -8223,7 +8274,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:8226: error: ambiguous option: $1
+    { { echo "$as_me:8277: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -8258,12 +8309,12 @@ Try \`$0 --help' for more information." >&2;}
   'config.h' ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
 
   # This is an error.
-  -*) { { echo "$as_me:8261: error: unrecognized option: $1
+  -*) { { echo "$as_me:8312: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
    { (exit 1); exit 1; }; } ;;
-  *) { { echo "$as_me:8266: error: invalid argument: $1" >&5
+  *) { { echo "$as_me:8317: error: invalid argument: $1" >&5
 echo "$as_me: error: invalid argument: $1" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -8411,7 +8462,7 @@ s,@SDL_CFLAGS@,$SDL_CFLAGS,;t t
 s,@SDL_LIBS@,$SDL_LIBS,;t t
 s,@NASM@,$NASM,;t t
 s,@NASMFLAGS@,$NASMFLAGS,;t t
-s,@EFENCE_LIBS@,$EFENCE_LIBS,;t t
+s,@AVIFILE_LAYER@,$AVIFILE_LAYER,;t t
 CEOF
 
 EOF
@@ -8526,7 +8577,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:8529: creating $ac_file" >&5
+    { echo "$as_me:8580: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -8544,7 +8595,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:8547: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:8598: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -8557,7 +8608,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:8560: error: cannot find input file: $f" >&5
+           { { echo "$as_me:8611: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -8618,7 +8669,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:8621: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:8672: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -8629,7 +8680,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:8632: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:8683: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -8642,7 +8693,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:8645: error: cannot find input file: $f" >&5
+           { { echo "$as_me:8696: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -8759,7 +8810,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:8762: $ac_file is unchanged" >&5
+      { echo "$as_me:8813: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
